### ISSUE TITLE
[SCT-LL]: Service the LL point data

### ISSUE THREAD

**Issue by trietmnj** [USACE/chart-docs#105]
a)	Service the government furnished LL point data for the web user interface (UI) and canvas through an endpoint accessible to USACE employees. The data includes annual exceedance frequencies (AEF) distributional information and three sensitivity scenarios according to the evacuation rate assumption.

**Comment by g-braide** [comment]
Update life-loss GET endpoint to include evacRate parameter.

`ex. /stapi/lifeloss?project_id={project_id}&slc=0&evacRate=0.6`
