### ISSUE TITLE
[SCT-EAD]: Summarize the additional EAD metrics

### ISSUE THREAD

**Issue by trietmnj** [USACE/chart-docs#116]
d)	Extend the EAD summary to include information on the inundation depth, wave height, and erosion. For each value of reach, occupancy type, damage category, and social vulnerability status (SV; i.e. in or outside an SV zone):
> i)	Summarize the count of EAD points and statistical mean, min/max range, and quartile information of inundation depth and wave height. Inundation depth and wave height should vary according to the selected AEF.
> ii)	Summarize the count of EAD points in or outside the erosion zone.

**Comment by g-braide** [comment]
add calculation to nsiEadSummary bundle
