### ISSUE TITLE
[Feature Request]: Study Setup

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#16]
### Background

Create / save a study scoping effort, designate the study as a test case or the official study scope effort

### User Story

User needs to be able to create and save the study scoping effort, designate the study as the category they require (for example a test study or an official study).

### Purpose

Administration to setup the study

### Workflow

Roles include:
- PTL
- PM
- Economist
- Engineer

**Comment by trietmnj** [comment]
Study creation is completed
