### ISSUE TITLE
[Feature Request]: Planning Reach Data Entry

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#26]
### Background

Populate planning reach attribute data/relation with planning reach identifier, characterize relevant exposure categories,  checkmark for pluvial risk possibility (Y/N)

### User Story

Spatially define pluvial hazard possibility; exposure risk components within SCT 

### Purpose

Identify Risk: develop & substantiate problems & opportunities / Define study objectives & constraints

### Workflow

Roles include:
- PTL
- Economist
- Engineer

**Comment by trietmnj** [comment]
Pluvial risk is not scoped within this work
