### ISSUE TITLE
[Feature Request]: NFIP Claims Data 

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#27]
### Background

View, display and/or report aggregated NFIP claims data such as number of claims and payout amount

### User Story

Easy access to problem supporting evidence within SCT environment; linkage to HIS and planning reach within SCT

### Purpose

Identify Risk: develop & substantiate problems & opportunities / Define study objectives & constraints

### Workflow

Roles include:
- Economist

**Comment by trietmnj** [comment]
Outside the scope of the SCT
