### ISSUE TITLE
[Feature Request]: Problem Statements

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#29]
### Background

Develop, view, display, and/or report problem statements for each planning reach &HSI combination. 

### User Story

Clearly developed problem statements and supporting evidence; linked to planning reach and HIS in SCT

### Purpose

Identify Risk: develop & substantiate problems & opportunities / Define study objectives & constraints

### Workflow

Roles include:
- PTL
- Economist

**Comment by trietmnj** [comment]
The tool is intended to provide scientific information- not PM functionalities
