### ISSUE TITLE
[Feature Request]: EAD, Consequences & RSLR

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#37]
### Background

View, display and/or report (EAD + consequences by AEF) by RSLC scenario within a study area boundary

### User Story

Scoping level risk & consequence quantification with RSLR

### Purpose

Quantify risk & consequences considering RSLR & Uncertainty

### Workflow

Roles include:
- PTL
- Economist
- Engineer

**Comment by trietmnj** [comment]
The ability to view EAD by SLC scenarios has been implemented
