### ISSUE TITLE
[Feature Request]: Study Task List

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#41]
### Background

View, display, update and/or reporta list of study tasks needed to accomplish the feasibility study based on SCT specification / models needed for the study in question

### User Story

Understand the tasks needed to execute the study

### Purpose

Develop study scope and cost /  Achieve vertical team alignment on scope / Mine SCT database for intel

### Workflow

Include the PDT and could include:
- PTL
- PM
- Economist
- Engineer

**Comment by trietmnj** [comment]
"Mine SCT database for intel" is not a good user story. This tool is not intended for PM determination, but rather to provide information for a scientific scope.
