### ISSUE TITLE
[Feature Request]: User Uploaded Media

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#42]
### Background

Upload view, display and/or report media such as georeferenced pictures, video and /or hyperlinks  that can be linked to planning reaches or HSIs as supporting evidence of issues within the study area. Team members should also be able to upload media to the study.

### User Story

Provide easily accessible media and additional corroborating info ; documenting and reporting purposes

### Purpose

Develop risk / benefit categories

### Workflow

Include the PDT and could include:
- PTL
- PM
- Economist
- Engineer

**Comment by trietmnj** [comment]
This tool is not intended for general PM purposes, but rather to provide information for a scientific scope.
