### ISSUE TITLE
[Feature Request]: Cultural Resource Impact Analysis

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#46]
### Background

View, display and/or report cultural resources within selected floodplain extent / risk area

### User Story

Understand and factor cultural resource impacts into plan formulation decisions

### Purpose

Develop risk / benefit categories

### Workflow

Roles include:
- Environmental/ Cultural

**Comment by trietmnj** [comment]
Cultural resources is outside the scope of this development effort.
