### ISSUE TITLE
[Feature Request]: display of reach shapefile

### ISSUE THREAD

**Issue by KHodgens** [USACE/chart-docs#5]
### Feature request item

1. remove shading of reach polygon as it interferes with the hazards displays
2. use only a boundary line of appropriate weight and line type
3.
...

### Is the feature related to problem

Yes Hazard viewing is not intuitive, this will help some

### Priority of requested feature.

Medium

### Feature alternatives

draw polygon in SCT and only display boundary

### Additional context

none

**Comment by trietmnj** [comment]
Will be included in the next UI update.

![image](https://github.com/USACE/chart-docs/assets/53122983/70ae869e-b008-40f0-9d03-c43557a27b70)
