### ISSUE TITLE
[Feature Request]: EAD, Consequences & Uncertainty

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#53]
### Background

View, display and/or report Uncertainty with all EAD & consequence estimates

### User Story

Risk and consequence estimates are reflected as a range

### Purpose

Quantify risk & consequences considering RSLR & Uncertainty

### Workflow

Roles include:
- Economist
- Engineer

**Comment by trietmnj** [comment]
EAD by SLR has been implemented
