### ISSUE TITLE
[Feature Request]: Measure Development

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#54]
### Background

Select, view, display, and/or report risk mitigation measures for each planning reach & HSI combination linked based on relevant erosion, inundation, and wave attack problem description, and measure primary function.

### User Story

Develop measures linked to hazard and physical conditions, problems, & opportunities

### Purpose

Develop measures / alternatives and perform affordability analysis 

### Workflow

Roles include:
- PTL
- Economist
- Engineer

**Comment by trietmnj** [comment]
This should be in the FET.
