### ISSUE TITLE
[Feature Request]: Measure / Alternative Development & Costs

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#55]
### Background

Calculate R.O.M. cost for selected structural and NNBF measures by allowing users to enter fixed and variable unit cost, and unit parameters to generate a range of R.O.M costs for structural and NNBF measures

### User Story

Estimate R.O.M. range of cost for structural & NNBF  measures for affordability analysis

### Purpose

Develop measures / alternatives and perform affordability analysis 

### Workflow

Roles include:
- PTL
- Economist
- Engineer

**Comment by trietmnj** [comment]
Please contact the Cost Engineering Center for any issue related to cost development
