### ISSUE TITLE
[Feature Request]: Non-Structural Measure Development

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#56]
### Background

Calculate R.O.M. cost for selected non-structural measures a polygon around a set of assets and indicate range of costs per asset for R.O.M nonstructural measure costs.

### User Story

Estimate R.O.M. range of cost for nonstructural  measures for affordability analysis

### Purpose

Develop measures / alternatives and perform affordability analysis 

### Workflow

Include the PDT and could include:
- PTL
- PM
- Economist
- Engineer

**Comment by trietmnj** [comment]
Please contact the Cost Engineering Center for any issue related to cost development
