### ISSUE TITLE
[Feature Request]: Scope Development

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#58]
### Background

Allow users & team members to select study tasks and enter the amount of effort / cost to execute tasks. Tool tabulates the total costs

### User Story

Estimate R.O.M. range of study cost

### Purpose

Develop study scope and cost /  Achieve vertical team alignment on scope / Mine SCT database for intel

### Workflow

Roles include:
- PTL
- PM

**Comment by trietmnj** [comment]
This tool is intended to provide scientific information- not PM functionalities
