### ISSUE TITLE
[Feature Request]: Scope COA Development

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#59]
### Background

Allow users & team members to create, define, multiple scope COAs, where users can select and deselect study tasks as needed and enter the effort/costs for the COAs. The SCT tabulates the overall costs for each COA.

### User Story

Estimate R.O.M. range of study cost for multiple scope COAs

### Purpose

Develop study scope and cost /  Achieve vertical team alignment on scope / Mine SCT database for intel

### Workflow

Roles include:
- PTL
- PM

**Comment by trietmnj** [comment]
This tool is intended to provide scientific information- not PM functionalities
