### ISSUE TITLE
[Feature Request]: Model Strategy & Scope COA Development

### ISSUE THREAD

**Issue by marko-nedzbala** [USACE/chart-docs#63]
### Background

Allow users,  team members, & decision makers to mine information from the scoping tool based on the aggregation of data entered into the tool over time.

### User Story

Extract information over time to inform enterprise level decision making or inform scoping assumptions for other efforts

### Purpose

Develop study scope and cost /  Achieve vertical team alignment on scope / Mine SCT database for intel

### Workflow

PDT and Decision-Makers

**Comment by trietmnj** [comment]
This tool is intended to provide scientific information- not PM functionalities. "Mine SCT database for intel" is a poorly defined scope. While the data are persistent and can be mined, this is outside the scope of the initial development.
