### ISSUE TITLE
[SCT-SV]: Developing workflow to update CJEST data

### ISSUE THREAD

**Issue by trietmnj** [USACE/chart-docs#86]
Update READMe and official documentation to call out the use of `CJEST_URL` within the dockerfile(https://github.com/USACE/screening-tool-api-support/blob/main/seed/cjest/Dockerfile). 

Noting if there is a change to this url that the dockerfile will need to be updated

**Comment by g-braide** [comment]
Script included in Docker container.

https://github.com/USACE/screening-tool-api-support/blob/main/seed/cjest/Dockerfile
