### ISSUE TITLE
[SCT-CI]: Append downloadable functionality to containing CI points

### ISSUE THREAD

**Issue by trietmnj** [USACE/chart-docs#93]
Geospatial download similar to current EAD download. 

GET: /project/:projectid/coastal_hazard_ci/download

**Comment by g-braide** [comment]
getting below error after large refactor PR

`{"time":"2024-11-07T20:00:05.025599369Z","level":"ERROR","msg":"REQUEST_ERROR","id":"","uri":"/stapi/project/01dbbe30-2453-4468-bf68-f75ba0a75711/coastal_hazard_ci/download","status":500,"err":"can't scan into dest[9]: cannot scan NULL into *string"}`

-EAD download still works (*implemented with a GET without access token)
-LL download still works (*implemented with a GET including access token)
